### PR TITLE
Update Angular

### LINKED ISSUE #44: Doesn't work for Angular 10
Even though the readme says that this works with Angular 5, 6, 7 and 8, I managed to install it on an angular 9 app with no problems.  Now that Angular 10 is out there, is there any plan to make it compatible with Angular 10?

### PR DESCRIPTION
**Pull request by electrofLy**
# Summary

Update from Angular8 to Angular10. 

This PR fixes #44.

### CODE REVIEW

**Comment by electrofLy** [comment]
@Arnaud73 will you have time to review this?

**Comment by tehZeno** [comment]
don't forget to update the angular versions mentioned in the readme :)

**Comment by sinsunsan** [comment]
Maybe a quick update to angular 11 ? 

How to use a version of this PR ? As I doubt the owner of this repo will merge one day 

  `"ngx-matamo": "https://github.com/electrofLy/ngx-matomo#b5bdef338f3bb2f2cdd078c36b640e9a0143fb1a"`
  
  this is valid ?

**Comment by electrofLy** [comment]
@sinsunsan I've updated it. You can use the new version.

Hopefully. @Arnaud73 checks this out some day.

**Comment by sinsunsan** [comment]
I feel dumb 

I tryed to install your forked package like this 
    "ngx-matamo": "electrofLy/ngx-matomo#hotfix/#44/update_to_angular_10"

or with the commit 

but using yarn I always end with 

```
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
[5/5] 🔨  Building fresh packages...
[1/41] ⠄ ngx-matamo
[2/41] ⠄ fsevents
[3/41] ⠄ core-js
[4/41] ⠄ node-sass
error /Users/slucas/www/app/node_modules/ngx-matamo: Command failed.
Exit code: 127
Command: ngcc
Arguments:
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
[5/5] 🔨  Building fresh packages...
[1/41] ⠄ ngx-matamo
[2/41] ⠄ fsevents
[3/41] ⠄ core-js
[4/41] ⠄ node-sass
error /Users/slucas/www/renault/boy-stack/app/node_modules/ngx-matamo: Command failed.
Exit code: 127
Command: ngcc
Arguments:
```

What did I missed ?

**Comment by sinsunsan** [comment]
I tried with a new project created with ng new 

yarn add electrofLy/ngx-matomo#hotfix/#44/update_to_angular_10

Here is the result 

Screen Shot 2021-02-23 at 23 18 07

**Comment by sinsunsan** [comment]
Seems to work with npm "ngx-matomo": "github:electrofLy/ngx-matomo#hotfix/#44/update_to_angular_10",

with 
`npm install electrofLy/ngx-matomo#hotfix/#44/update_to_angular_10 --save`

will test with the `github:` prefix in the package.json

**Comment by aaronbach** [comment]
@sinsunsan did you get it to work? The installation you mentioned with `npm` worked fine for me.
I cannot import from this PR like so:
```
import { MatomoInjector, MatomoTracker } from 'ngx-matomo';
```

I get `Cannot find module 'ngx-matomo' or its corresponding type declarations.`.

Do you can point out, how to use this MR?

**Pull request closed without merging**
