### PR TITLE
feat(deps): add support for Angular 17

### PR DESCRIPTION
**Pull request by WikiRik**
As demonstrated in this PR, Angular 17 support can be added out of the box. Although Angular 17 does increase the requirements for TypeScript and Node versions to 5.2 and 18.13 respectively which might warrant another major release depending on your vision. Therefore I've not added it to the README.

Let me know what the vision is and I can update this draft PR accordingly.

### CODE REVIEW

**Comment by bertrand-ravier** [comment]
+1, need this to upgrade Angular to v17

**Comment by tarlepp** [comment]
Angular `17.1.0` is released.

Any progress with this pull request?

**Comment by andyjmaclean** [comment]
Will this get published to [npm](https://www.npmjs.com/package/ngx-matomo) for compatibility with Angular 17.x apps?

**Comment by tarlepp** [comment]
Angular `17.2.0` is released.

Any progress with this pull request?

**Comment by MrFrontend** [comment]
For anyone wondering how to do this in angular > 16.0.0 Matomo recommends now to use this library instead:
https://github.com/EmmanuelRoux/ngx-matomo-client

You can see this on the official integration page:
https://matomo.org/integrate/

**Pull request closed without merging**
